### ISSUE TITLE
"autoBindSteps" doesn't work with Scenario Outline

### ISSUE THREAD

**Issue by closetpriyesh** [bencompton/jest-cucumber#100]
@bencompton 
Hi, I tried using "autoBindSteps" for scenario outline but I got error at **Object.exports.checkThatFeatureFileAndStepDefinitionsHaveSameScenarios**

I made the scenario name as another parameter to be picked up from one of the examples hoping that would interpret every test example as different scenario but that also didn't work.

I did something like this.

Scenario Outline: <element> test
When user is on home page
user verifies <element>

Examples:

|element|
| button |
| input  |

Please help. Thanks!

**Comment by bencompton** [comment]
The examples have scenario outlines working with `autoBindSteps`. I don't quite follow what the issue is, so perhaps you could provide more details about how to reproduce? From your example, it appears there is a syntax error in the Gherkin, so not sure if that is causing any issues. I'm assuming `user verifies` should be `Then user verifies`, but that might have just been a typo.

**Comment by closetpriyesh** [comment]
Thanks Ben for the quick reply. Actually, I misunderstood the functionality a bit but now got it. It actually binds the steps  when we provide all the steps included in each of the feature. I was thinking the other way like it will just attach the steps being provided to each feature and then missing steps can be defined later. But this is really cool. Thanks Ben. I will be closing this.!!
