### ISSUE TITLE
Why does the package require a test() for each scenario?

### ISSUE THREAD

**Issue by mull** [bencompton/jest-cucumber#11]
Normally, as far as I am aware, one never matches on scenarios, since they should all be different tests for the same feature. What's the reason for having to write `test(scenario_name)` instead of simply providing the feature and the step matchers?

**Comment by bencompton** [comment]
The goal is to improve readability by having the step definitions read more like the feature file, and also be structured somewhat more like typical Jest scenarios. Cucumber does not validate the ordering or even the location of step definitions, whereas this library validates that all step definitions are listed in order under each scenario block. This reduces the mental overhead when reasoning about test code, because it is no longer necessary to constantly cross-reference between the feature files and the step definitions. The trade-off for this improved readability is that step definition code still be re-used if abstracted into another function, but that function must then be called from every scenario that requires it, which is more verbose than Cucumber's approach to step definition re-usability.

**Comment by mull** [comment]
As I spent a few more hours with it last night I sort of see why things are this way. Having used Cucumber in Ruby it annoyed me greatly to have to match on each scenario since typically one would just add a scenario with new steps and not having to update any matchers (given that no step was new, of course.)

I kind of see the rationale, I guess. Definitely works out better in jest! Thanks for the explanation 😊
