### ISSUE TITLE
Support for repeated steps

### ISSUE THREAD

**Issue by jan-musi** [bencompton/jest-cucumber#139]
On [this line](https://github.com/bencompton/jest-cucumber/blob/1a9ef75f5602d5b18dd4b33d08130e878799da59/src/validation/step-definition-validation.ts#L49), an error is thrown if a feature's step count doesn't match its step definition count. However, this precludes features with repeated steps.

Example:
```
Scenario: Walking to my friend's house
  Given I am at my house
  And I walk two blocks north
  And I walk one block east
  And I walk two blocks north
  When I look east
  Then I should see my friend's house
```

I currently cannot reuse one definition like this:
```
and("I walk two blocks north", async () => {
  ...
}
```
because then I would receive the error `Scenario "Walking to my friend's house" has 6 step(s) in the feature file, but 5 step definition(s) defined.`

Additionally, if I tried to reuse one step definition for all walking, like this:
```
and(/^I walk (.+?) blocks? (.+?)$/, async (blockCount: string, direction: string) => {
  ...
}
```
then I would receive the error `Scenario "Walking to my friend's house" has 6 step(s) in the feature file, but 4 step definition(s) defined.`

I imagine that others would value support for this use case, but I see that this behavior is very much unexpected/unsupported. Is this because Gherkin features are not supposed to repeat themselves?

Thank you for this great library! :)

**Comment by sledorze** [comment]
Same issue, can you provide some feedback?

**Comment by bencompton** [comment]
This is actually by design. In the default "Jest mode", Jest Cucumber expects your steps to match your feature files exactly, and the goal is that you keep your Jest tests in sync with your feature files. Duplicated code can be reduced by following the pattern described [here](https://github.com/bencompton/jest-cucumber/blob/master/docs/ReusingStepDefinitions.md). If you prefer behavior similar to Cucumber where step definitions are defined once and are matched globally to feature file steps, then you might want to look into [autoBindSteps](https://github.com/bencompton/jest-cucumber/blob/master/docs/AutomaticStepBinding.md).
