### ISSUE TITLE
Feature Output

### ISSUE THREAD

**Issue by cappelaere** [bencompton/jest-cucumber#14]
When I run the test, I only see a green checkmark at the scenario level and not the individual steps that passed.  Am I missing something?  Could this be configurable?
When a feature is not implemented, it displays a gray circle and says skipped 1 test.  Would it be possible to output the name of the test and have (skipped) at the end so you know which feature was skipped (or what step was skipped)?
Thanks.
Pat.

**Comment by bencompton** [comment]
In this library, each scenario is considered a Jest test, and the the individual steps are just components of that test. In the vscode-jest extension, it looks for the keyword `test` in order to know where to put the status dot and won't put a status dot next to blocks not called `test` (or `it` or `describe`). So, putting status dots next to `given` `when` or `then` blocks doesn't seem to be an option.

**Comment by cappelaere** [comment]
Since we use it for Acceptance Tests, it would be great to see those checkmarks!

**Comment by bencompton** [comment]
Accomplishing that would require either restructuring the API so that every step can be a separate test (and every step would need to be within a `test` block, which would not be so clean IMO), or otherwise modifying the vscode-jest extension somehow. Either way, it wouldn't be a small effort.

In my view, the output in the IDE is already pretty clear. When all steps are passing, the scenario has a green dot, and when a step is failing, the scenario has a red dot, and then there is a red squiggly within the failing step:

![step_failure](https://user-images.githubusercontent.com/3343482/43002805-215680e4-8bf8-11e8-964c-b7d5c4b6ee8a.png)

To me, it seems more of a matter of aesthetic preference whether or not to show green dots only on the scenario and have red squigglies for failing steps, vs. having green or red dot on every individual step. Perhaps I don't entirely understand your viewpoint, so free to elaborate on what you're trying to accomplish or provide more details about your pain points.

**Comment by cappelaere** [comment]
If you use the IDE and test one feature, this is fine.
If you have to test 100 features with each running 100 steps, then a summary page is important to see what passed, what was skipped and what failed.  Right now, we only have visibility of pass/fail at the feature level (but we can't tell exactly what was skipped).  Since the tests take a long time, it would be great to see the individual step statuses as they happen.  Thanks. Pat.

**Comment by bencompton** [comment]
Have you tried [Majestic](https://github.com/Raathigesh/majestic). It is a nice compliment to the vscode-jest plug-in and gives you a better overview of what is passing and failing.

**Comment by bencompton** [comment]
In Majestic, here is what you would see in the case of a failing step:

![image](https://user-images.githubusercontent.com/3343482/43004406-ae613042-8bfd-11e8-81a3-30fb1fb7e1a6.png)

You can then click the link on the failing scenario, and it will take you straight into VS Code where you will then see the failing step with red squigglies and debug / fix the issues.
