### ISSUE TITLE
@storybook/jest compatibility

### ISSUE THREAD

**Issue by jcamden** [bencompton/jest-cucumber#169]
Thank you so much, @bencompton, for this great package. It's been a tremendous help for us satisfying BDD requirements (feature files with scenarios we can sync to JIRA) while being able to stay as lightweight as possible with jest and @testing-library/react.

Lately, however, we're moving towards @storybook/react (with @storybook/interactions, @storybook/jest, and @storybook/testing library) especially in light of the automatic visual regression testing of stories with chromatic. As wonderful as we feel about that approach to frontend testing, it remains to be seen how we could integrate BDD. My first thought, of course, was to look into compatibility with jest-cucumber. I can't quite think of how it would work, unfortunately. The logic for steps would now be defined inside of the `play` methods of stories, rather than the .steps file we are used to running with jest and jest-cucumber.

Do you have any insights or tips (or interest) regarding compatibility between jest-cucumber and BDD? I sincerely appreciate your time!

**Comment by bencompton** [comment]
The short answer is that I don't feel that Gherkin is the best tool for the job regarding visual regression tests, or really anything outside of acceptance tests. Visual regression tests, unit tests, etc., don't really benefit from Gherkin, IMO. The purpose of Gherkin is to describe business rules and link them to automated tests. I always encourage my teams to eliminate all UI terminology from feature files because the focus should be on the rules, not the look and feel of the UI.

My philosophy is that other types of tests, like visual regression, can focus on the UI, and can use tools that are more appropriate for the job. IMO, the goal of feature files should be to concisely tell a story and provide key examples to demonstrate behavior, rather than being a dumping ground for every possible testing concern. That being said, using the same test runner (Jest) for acceptance tests and other types of tests is nice.
