### ISSUE TITLE
Background setup

### ISSUE THREAD

**Issue by lucasmafra** [bencompton/jest-cucumber#2]
Hi,

I found nothing in the docs about setting up the [Cucumber Background](https://github.com/cucumber/cucumber/wiki/Background) in the step definitions. Since the given, when and then callbacks are available inside each test (scenario), how can I setup a background that is common for all scenarios in a feature (as I can do with Cucumber)?

**Comment by bencompton** [comment]
Backgrounds are currently not supported. Personally, I don't find myself using `Background` very often, and was waiting to see if anyone else asked for it. I do agree that it would definitely be worth implementing.

One way to work around that for the time being would be to use Jest `beforeEach` hooks, since that would allow you to run setup code before each scenario. Of course, your setup steps wouldn't be documented in your Feature file with that approach.

**Comment by robinelvin** [comment]
I would welcome this enhancement. We use common set up steps which are listed in the Background section. Currently we use the beforeEach hook for this but of course these aren't tied to the Feature so can get out of sync.

**Comment by pedrowilkens** [comment]
how would this be implemented ?  
Would it just replace beforeEach ? Should it be validated i.e. a test, Since the scenarios would fail if it fails ? If it would be a test should it be run once as a test and then be a normal function ? So it would only tested once at the beginning aand appear onced in the reporter. 

Would it be exposed like this ?
```javascript
import { defineFeature } from 'jest-cucumber'

defineFeature(feature, (test, background) => {

})

```

I Would like to discuss this a little because i would offer my help.

**Comment by bencompton** [comment]
That's right, background would end up calling beforeEach instead of test, and it would be declared just like your example. The parsing logic would need to be updated to extract the background scenario(s), and it should be able to re-use the existing logic to parse scenarios. Then the scenario definition / execution logic would need to be updated to handle background scenarios. Other than running background scenarios in `beforeEach` instead of `test`, most of the logic for processing scenarios should be reusable.

**Comment by sebastianspiller** [comment]
Hi, thanks for implementing the background feature. I do really appreciate your work. It's great that this project is so vivid and that there is such a support of the community. Could you tell me, what advantage the use of beforeEach for "background" has? I'd like to use beforeEach for my setup and by reusing beforeEach as background, would the beforeEach feature overwritten? Or would it be possible to use beforeEach and background together?

**Comment by bencompton** [comment]
@sebastianspiller - You should be able to use them together. Declaring a background would end up declaring a Jest `beforeEach` behind the scenes, and the order in which they execute would depend on the order in which they are declared. The advantage of using background instead of `beforeEach` is that a background is a scenario in your feature file that runs before every other scenario.

**Comment by axcosta** [comment]
One thing to have in mind when implementing it is that currently (as it seems) test requires givens,whens and thens, so with a background setup, maybe you wouldn't have all these other steps configured for each test.

**Comment by ian7** [comment]
For everyone interested - I've made background steps work here: https://github.com/ian7/jest-cucumber/tree/background

**Comment by techaltumnoida15** [comment]
ian7: 
Solution given by you about Background is not working. Could you please explain it.
It says that Steps in Feature and Test doesnt match.

**Comment by techaltumnoida15** [comment]
> Backgrounds are currently not supported. Personally, I don't find myself using `Background` very often, and was waiting to see if anyone else asked for it. I do agree that it would definitely be worth implementing.
> 
> One way to work around that for the time being would be to use Jest `beforeEach` hooks, since that would allow you to run setup code before each scenario. Of course, your setup steps wouldn't be documented in your Feature file with that approach.

@dbartholomae : In UI automamtion, Background use frequently because there could be many tests which use Background.
I hope, there will be a working solution soon. Meanwhile, could you please suggest a solution for it.

Thanks in advance.

**Comment by bencompton** [comment]
Backgrounds are now implemented and will go out in a release later today. See the [docs](https://github.com/bencompton/jest-cucumber/blob/master/docs/Backgrounds.md) and [examples](https://github.com/bencompton/jest-cucumber/blob/master/examples/typescript/specs/step-definitions/backgrounds.steps.ts) for more info.
