### ISSUE TITLE
Set some examples in Scenario Outline to be in pending state

### ISSUE THREAD

**Issue by angeloinqbyte** [bencompton/jest-cucumber#98]
I've checked the documentation and couldn't find if its possible to have some examples in a scenario outline test to be set to pending? I've tried running pending in some examples and it still returns as success/check. Can anyone help me about this?

**Comment by bencompton** [comment]
The only way to have some examples pending would be if those examples map to step definitions that are specific to those examples, rather than one catch-all step definition for all examples. For example, `Given I have <amount> marbles` would map to `given('I have 5 marbles)` and given('I have 10 marbles') rather than `given('I have  (\d+) marbles')`, and then the 5 marbles step definition can be pending and the other could be not pending. I haven't tried it, but this might work with the `autoBindSteps` approach. With this normal Jest Cucumber setup, this would cause validation errors, since it would be expecting to see one step definition for each step in the feature file, whereas you would have multiple step definitions.
