### ISSUE TITLE
Reading external file in example table of scenario outline inside .feature file

### ISSUE THREAD

**Issue by manavbharaduaj** [bencompton/jest-cucumber#99]
Hi, I need to read external json file in Example table of scenario outline inside feature file. Can you please look into this our organization will be highly in debt of you if you take this into your concern at the earliest.
Atleast if we could specify file path in a column of example table then it can rad and map the file to the parameter of the callback associated with the statement
This will be helpful.

I would be requeating onw morw thing if possible that we can give a way to call a javascript function in table iniside feature file

**Comment by bencompton** [comment]
If you have a JSON file with example data then perhaps you can read that from your step definition code, since that's not "business readable" information that belongs in the feature file anyhow. I'm not sure why you would want JavaScript in your feature file unless you are describing an extremely technical feature, in which case, perhaps you would be better off not bothering with feature files that target non-engineers (Jest by itself might be more appropriate)? I mean, you can certainly put JavaScript in your Gherkin and then use the `eval` statement in your step definition, but that's probably not the best design.
